Avoid TypeError upon validation
Entire error: 
'''
File "/anaconda3/lib/python3.6/site-packages/pandas_schema/validation.py", line 375, in default_message
    return 'is not in the list of legal options ({})'.format(', '.join(self.options))
TypeError: sequence item 0: expected str instance, int found
'''

Caused when item in list is int and not a string.

Alternative formats to string before concatenating.